apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kpoz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kpoz
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-kpoz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-kpoz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-kpoz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ihkz-tenant/rhtap-demo-app/hacbs-test-project-kpoz@sha256:4062624260f7b406a9d2299799e010cd1edfbefa03571615718b3b23962afb05
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
